services:
  - type: web
    name: crm-tu-visa-mundo
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run crm_app.py --server.port $PORT"
