import templates from "../data/mensajes.json";
import { addDays } from "./dates";
import type { CrmData, Lead, Message } from "./types";

export function createMockData(date: string): CrmData {
  const base: Lead = {
    id: "lead-001",
    version: 0,
    nombre: "Juan",
    apellido: "Pérez",
    whatsapp: "+54 11 5555 0001",
    email: "juan@example.com",
    destino: "Canadá",
    tipoVisa: "Turismo",
    origen: "Landing Canadá",
    segmento: "SIN_ESTUDIO",
    tipoEstudio: "NINGUNO",
    secuenciaId: "sin-estudio-canada",
    fechaIngreso: date,
    estado: "NUEVO",
    proximoContacto: date,
    proximaAccion: "Enviar primer mensaje",
    proximoMensajeId: "sin-estudio-canada-1",
    seguimientoManual: false,
    secuenciaPausada: false,
    asesor: "Asesor principal",
  };
  return {
    mensajes: structuredClone(templates as Message[]),
    interacciones: [],
    leads: [
      base,
      {
        ...base,
        id: "lead-002",
        nombre: "María",
        apellido: "Gómez",
        email: undefined,
        whatsapp: "+57 300 555 0002",
        destino: "Estados Unidos",
        secuenciaId: "sin-estudio-eeuu",
        origen: "Meta Ads",
        fechaIngreso: addDays(date, -3),
        estado: "SEGUIMIENTO",
        ultimoContacto: `${addDays(date, -2)}T15:00:00Z`,
        ultimoMensajeId: "sin-estudio-eeuu-1",
        proximoContacto: addDays(date, -1),
        proximaAccion: "Enviar seguimiento inicial",
        proximoMensajeId: "sin-estudio-eeuu-2",
      },
      {
        ...base,
        id: "lead-003",
        nombre: "Andrés",
        apellido: "Ruiz",
        email: undefined,
        whatsapp: "+57 315 555 0003",
        destino: "Canadá",
        origen: "Instagram orgánico",
        segmento: "ESTUDIO_A",
        tipoEstudio: "GRATUITO",
        perfilEstudio: "A",
        secuenciaId: "estudio-canada",
        fechaIngreso: addDays(date, -6),
        estado: "SEGUIMIENTO",
        ultimoContacto: `${addDays(date, -3)}T15:00:00Z`,
        ultimoMensajeId: "estudio-canada-1",
        proximaAccion: "Enviar resultado del estudio de perfil",
        proximoMensajeId: "estudio-canada-2-ab",
      },
      {
        ...base,
        id: "lead-004",
        nombre: "Laura",
        apellido: "Martínez",
        email: undefined,
        whatsapp: "+54 9 11 5555 0004",
        destino: "Reino Unido",
        secuenciaId: "sin-estudio-uk",
        origen: "Lista de documentos",
        fechaIngreso: addDays(date, -11),
        estado: "EN_CONVERSACION",
        ultimoContacto: `${addDays(date, -2)}T15:00:00Z`,
        proximaAccion: "Invitar al estudio gratuito en línea",
        proximoMensajeId: "sin-estudio-uk-2",
        seguimientoManual: true,
        secuenciaPausada: true,
      },
    ],
  };
}
