import templates from "../data/mensajes.json";
import { addDays } from "./dates";
import type { CrmData, Lead } from "./types";

export function createMockData(date: string): CrmData {
  const base: Lead = {
    id: "lead-001",
    version: 0,
    nombre: "Juan",
    apellido: "Pérez",
    whatsapp: "+54 11 5555 0001",
    email: "juan@example.com",
    destino: "Canadá",
    tipoVisa: "Turismo",
    origen: "Landing Canadá",
    fechaIngreso: date,
    estado: "NUEVO",
    proximoContacto: date,
    proximaAccion: "Enviar primer mensaje",
    proximoMensajeId: "registro-1",
    seguimientoManual: false,
    secuenciaPausada: false,
    asesor: "Asesor principal",
  };
  return {
    mensajes: structuredClone(templates),
    interacciones: [],
    leads: [
      base,
      {
        ...base,
        id: "lead-002",
        nombre: "María",
        apellido: "Gómez",
        email: undefined,
        whatsapp: "+57 300 555 0002",
        destino: "Estados Unidos",
        origen: "Meta Ads",
        fechaIngreso: addDays(date, -3),
        estado: "SEGUIMIENTO",
        ultimoContacto: `${addDays(date, -2)}T15:00:00Z`,
        ultimoMensajeId: "registro-1",
        proximoContacto: addDays(date, -1),
        proximaAccion: "Enviar seguimiento inicial",
        proximoMensajeId: "registro-2",
      },
      {
        ...base,
        id: "lead-003",
        nombre: "Andrés",
        apellido: "Ruiz",
        email: undefined,
        whatsapp: "+57 315 555 0003",
        destino: "Australia",
        origen: "Instagram orgánico",
        fechaIngreso: addDays(date, -6),
        estado: "SEGUIMIENTO",
        ultimoContacto: `${addDays(date, -3)}T15:00:00Z`,
        ultimoMensajeId: "registro-2",
        proximaAccion: "Enviar último seguimiento",
        proximoMensajeId: "registro-3",
      },
      {
        ...base,
        id: "lead-004",
        nombre: "Laura",
        apellido: "Martínez",
        email: undefined,
        whatsapp: "+54 9 11 5555 0004",
        destino: "Reino Unido",
        origen: "Lista de documentos",
        fechaIngreso: addDays(date, -11),
        estado: "EN_CONVERSACION",
        ultimoContacto: `${addDays(date, -2)}T15:00:00Z`,
        proximaAccion: "Retomar conversación y confirmar fecha de viaje",
        proximoMensajeId: "manual",
        seguimientoManual: true,
        secuenciaPausada: true,
      },
    ],
  };
}
