import type { Lead } from './types';

export const sampleLeads: Lead[] = [
  {
    id: 'lead-001',
    nombre: 'Juan',
    apellido: 'Pérez',
    whatsapp: '+54 11 5555 0001',
    email: 'juan@example.com',
    destino: 'Canadá',
    tipoVisa: 'Turismo',
    origen: 'Landing Canadá',
    fechaIngreso: '2026-09-14',
    estado: 'NUEVO',
    prioridad: 'NUEVO',
    proximoContacto: '2026-09-14',
    proximaAccion: 'Enviar primer mensaje',
    mensajeNumero: 1,
    mensajeTexto: 'Hola Juan, ¿cómo estás? Te escribo porque te registraste en nuestro sitio web y nos indicaste que deseas tramitar la visa de turismo para Canadá. ¿Para cuántas personas sería el trámite?',
    asesor: 'Asesor principal',
  },
  {
    id: 'lead-002',
    nombre: 'María',
    apellido: 'Gómez',
    whatsapp: '+57 300 555 0002',
    destino: 'Estados Unidos',
    tipoVisa: 'Turismo',
    origen: 'Meta Ads',
    fechaIngreso: '2026-09-11',
    estado: 'SEGUIMIENTO',
    prioridad: 'ATRASADO',
    ultimoContacto: '2026-09-12',
    proximoContacto: '2026-09-13',
    proximaAccion: 'Enviar seguimiento 2',
    mensajeNumero: 2,
    mensajeTexto: 'Hola María, quería retomar tu consulta sobre la visa de turismo para Estados Unidos. Si todavía estás evaluando el trámite, puedo orientarte sobre el siguiente paso.',
    asesor: 'Asesor principal',
  },
  {
    id: 'lead-003',
    nombre: 'Andrés',
    apellido: 'Ruiz',
    whatsapp: '+57 315 555 0003',
    destino: 'Australia',
    tipoVisa: 'Turismo',
    origen: 'Instagram orgánico',
    fechaIngreso: '2026-09-08',
    estado: 'SEGUIMIENTO',
    prioridad: 'HOY',
    ultimoContacto: '2026-09-10',
    proximoContacto: '2026-09-14',
    proximaAccion: 'Enviar seguimiento 3',
    mensajeNumero: 3,
    mensajeTexto: 'Hola Andrés. Te comparto este seguimiento sobre tu proceso para Australia. Si quieres, podemos revisar primero tu perfil y orientarte antes de iniciar el trámite.',
    asesor: 'Asesor principal',
  },
  {
    id: 'lead-004',
    nombre: 'Laura',
    apellido: 'Martínez',
    whatsapp: '+54 9 11 5555 0004',
    destino: 'Reino Unido',
    tipoVisa: 'Turismo',
    origen: 'Lista de documentos',
    fechaIngreso: '2026-09-03',
    estado: 'EN_CONVERSACION',
    prioridad: 'MANUAL',
    ultimoContacto: '2026-09-12',
    proximoContacto: '2026-09-14',
    proximaAccion: 'Retomar conversación y confirmar fecha de viaje',
    mensajeTexto: 'Hola Laura, retomo nuestra conversación como acordamos. ¿Ya tienes definida la fecha aproximada en la que te gustaría viajar al Reino Unido?',
    conversacionActiva: true,
    asesor: 'Asesor principal',
  },
];
